spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zweb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: opzpy123
  flyway:
    enabled: true
    encoding: UTF-8
    validate-on-migrate: true
    clean-disabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password: opzpy123
      database: 1
  kafka:
    bootstrap-servers: localhost:9092
    concurrency: 1 #并发数 小于或等于分区数
    consumer:
      group-id: ZWeb3Group
      enable-auto-commit: false
      max-poll-records: 4000
      auto-commit-interval: 1000
      auto-offset-reset: earliest
    producer:
      retries: 3
      batch-size: 1000
      buffer-memory: 33554432
