####################################### server 配置 ####################################
server.port: 8080
####################################### spring 配置 ####################################
spring:
  profiles.active: local
  application.name: zweb

